### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by gBasil** [MrGcGamer/LibGcUniversalDocumentation#3]
dominantColor should be changed to dominantColors in line 372 of the readme

**Comment by gBasil** [comment]
Also, another question just for clarification. Is it guaranteed that the function will return an array with at least one color? You didn't open source the source, just the binary, so I'm not sure. Would be nice to say in the readme

**Comment by MrGcGamer** [comment]
Yes it will always return at least one color.
