### ISSUE TITLE
select file from gallery 

### ISSUE THREAD

**Issue by skndrvoip** [MrGcGamer/LibGcUniversalDocumentation#5]
![4551D2C8-A818-4363-B66E-3214AF5D1ACA](https://user-images.githubusercontent.com/23005748/234429345-b3b36909-2005-4c93-9648-d5cf415ba87f.png)
i have this problem if i install NoInAppSafari tweak if i uninstall this tweak its works fine Fugu15 Max Beta 8 rootless

**Comment by MrGcGamer** [comment]
~~Please ask the tweak dev for further assistance.~~ Please contact me on Discord or Twitter, to further investigate the issue at hand. (_MrGcGamer_#9738)
